// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useCallback, useEffect } from 'react';
import React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a from 'react';
import * as React from 'react';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import { cn } from 'components/lib/utils';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import { useRouter } from 'next/navigation';
import { usePreviewSearchActions, useSearchResultsActions, WidgetDataType, useSearchResults, widget, usePreviewSearch, FilterEqual, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import { PreviewSearch, SortSelect, Pagination, AccordionFacets, FacetItem, RangeFacet, SearchResultsAccordionFacets, SearchResultsFacetValueRange, Select, ArticleCard, CardViewSwitcher as CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 } from '@sitecore-search/ui';
import { GridIcon, ListBulletIcon, ArrowLeftIcon, ArrowRightIcon, CheckIcon } from '@radix-ui/react-icons';
import { HIGHLIGHTED_ARTICLES_RFKID, SEARCH_WIDGET_ID, PREVIEW_WIDGET_ID, HOMEHIGHLIGHTED_WIDGET_ID, DEFAULT_IMG_URL } from '@/_data/customizations';
import HomeHighlighted from 'src/components/search/HomeHighlighted';
import Spinner from 'src/components/search/Spinner';
import ArticleItemCard from 'src/components/search/ArticleCard';
import SortOrder from 'src/components/search/SortOrder';
import ArticleHorizontalItemCard from 'src/components/search/ArticleHorizontalCard';
import SearchPagination from 'src/components/search/SearchPagination';
import SearchFacets from 'src/components/search/SearchFacets';
import ResultsPerPage from 'src/components/search/ResultsPerPage';
import QueryResultsSummary from 'src/components/search/QueryResultsSummary';
import CardViewSwitcher from 'src/components/search/CardViewSwitcher';
import { useSearchTracking } from 'src/hooks/useSearchTracking';
import SearchResultsWidget from 'src/components/search/SearchResultsComponent';
import Image from 'next/image';
import SuggestionBlock from 'src/components/search/SuggestionBlock';
import { Context, getWidgetData, SearchWidgetItem, WidgetRequestData } from '@sitecore-cloudsdk/search/browser';
import Link from 'next/link';
import { Placeholder, Text, withDatasourceCheck, Link as Link_8a80e63291fea86e0744df19113dc44bec187216, RichText, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, CdpHelper, useSitecore, DateField } from '@sitecore-content-sdk/nextjs';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Bell, Zap, Facebook, Twitter, Instagram, Linkedin, Youtube, Thermometer, Activity, TrendingUp, TrendingDown, ArrowRight, Calendar, User, Share2, ChevronLeft, Bookmark } from 'lucide-react';
import { Button } from '@/components/ui/button';
import IconRenderer from '@/helpers/IconRenderer';
import PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 from 'src/components/search/PreviewSearch';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { AreaChart } from '@/components/charts/AreaChart';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { RiArrowLeftSLine, RiArrowRightSLine } from '@remixicon/react';
import { Area, CartesianGrid, Dot, Label, Line, AreaChart as AreaChart_2df1a179946854cc8ade8dd3596c5568763677e1, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AvailableChartColors, constructCategoryColors, getColorClassName, getYAxisDomain, hasOnlyOneValueForKey } from '@/components/lib/chartUtils';
import { useOnWindowResize } from '@/helpers/useOnWindowResize';
import { cx } from '@/components/lib/utils';
import { newsDateFormatter } from 'src/helpers/DateHelper';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useCallback', value: useCallback },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a },
      { name: '*', value: React },
    ]
  },
  {
    module: '@radix-ui/react-progress',
    exports: [
      { name: '*', value: ProgressPrimitive },
    ]
  },
  {
    module: 'components/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'usePreviewSearchActions', value: usePreviewSearchActions },
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'useSearchResults', value: useSearchResults },
      { name: 'widget', value: widget },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'useSearchResultsSelectedFilters', value: useSearchResultsSelectedFilters },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'PreviewSearch', value: PreviewSearch },
      { name: 'SortSelect', value: SortSelect },
      { name: 'Pagination', value: Pagination },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'RangeFacet', value: RangeFacet },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
      { name: 'SearchResultsFacetValueRange', value: SearchResultsFacetValueRange },
      { name: 'Select', value: Select },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'CardViewSwitcher', value: CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'GridIcon', value: GridIcon },
      { name: 'ListBulletIcon', value: ListBulletIcon },
      { name: 'ArrowLeftIcon', value: ArrowLeftIcon },
      { name: 'ArrowRightIcon', value: ArrowRightIcon },
      { name: 'CheckIcon', value: CheckIcon },
    ]
  },
  {
    module: '@/_data/customizations',
    exports: [
      { name: 'HIGHLIGHTED_ARTICLES_RFKID', value: HIGHLIGHTED_ARTICLES_RFKID },
      { name: 'SEARCH_WIDGET_ID', value: SEARCH_WIDGET_ID },
      { name: 'PREVIEW_WIDGET_ID', value: PREVIEW_WIDGET_ID },
      { name: 'HOMEHIGHLIGHTED_WIDGET_ID', value: HOMEHIGHLIGHTED_WIDGET_ID },
      { name: 'DEFAULT_IMG_URL', value: DEFAULT_IMG_URL },
    ]
  },
  {
    module: 'src/components/search/HomeHighlighted',
    exports: [
      { name: 'default', value: HomeHighlighted },
    ]
  },
  {
    module: 'src/components/search/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/components/search/ArticleCard',
    exports: [
      { name: 'default', value: ArticleItemCard },
    ]
  },
  {
    module: 'src/components/search/SortOrder',
    exports: [
      { name: 'default', value: SortOrder },
    ]
  },
  {
    module: 'src/components/search/ArticleHorizontalCard',
    exports: [
      { name: 'default', value: ArticleHorizontalItemCard },
    ]
  },
  {
    module: 'src/components/search/SearchPagination',
    exports: [
      { name: 'default', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/search/SearchFacets',
    exports: [
      { name: 'default', value: SearchFacets },
    ]
  },
  {
    module: 'src/components/search/ResultsPerPage',
    exports: [
      { name: 'default', value: ResultsPerPage },
    ]
  },
  {
    module: 'src/components/search/QueryResultsSummary',
    exports: [
      { name: 'default', value: QueryResultsSummary },
    ]
  },
  {
    module: 'src/components/search/CardViewSwitcher',
    exports: [
      { name: 'default', value: CardViewSwitcher },
    ]
  },
  {
    module: 'src/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking },
    ]
  },
  {
    module: 'src/components/search/SearchResultsComponent',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: 'src/components/search/SuggestionBlock',
    exports: [
      { name: 'default', value: SuggestionBlock },
    ]
  },
  {
    module: '@sitecore-cloudsdk/search/browser',
    exports: [
      { name: 'Context', value: Context },
      { name: 'getWidgetData', value: getWidgetData },
      { name: 'SearchWidgetItem', value: SearchWidgetItem },
      { name: 'WidgetRequestData', value: WidgetRequestData },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'Text', value: Text },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
      { name: 'DateField', value: DateField },
    ]
  },
  {
    module: '@/components/ui/card',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardHeader', value: CardHeader },
      { name: 'CardTitle', value: CardTitle },
      { name: 'CardContent', value: CardContent },
      { name: 'CardDescription', value: CardDescription },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Bell', value: Bell },
      { name: 'Zap', value: Zap },
      { name: 'Facebook', value: Facebook },
      { name: 'Twitter', value: Twitter },
      { name: 'Instagram', value: Instagram },
      { name: 'Linkedin', value: Linkedin },
      { name: 'Youtube', value: Youtube },
      { name: 'Thermometer', value: Thermometer },
      { name: 'Activity', value: Activity },
      { name: 'TrendingUp', value: TrendingUp },
      { name: 'TrendingDown', value: TrendingDown },
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'Calendar', value: Calendar },
      { name: 'User', value: User },
      { name: 'Share2', value: Share2 },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'Bookmark', value: Bookmark },
    ]
  },
  {
    module: '@/components/ui/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: '@/helpers/IconRenderer',
    exports: [
      { name: 'default', value: IconRenderer },
    ]
  },
  {
    module: 'src/components/search/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'clsx', value: clsx },
    ]
  },
  {
    module: 'tailwind-merge',
    exports: [
      { name: 'twMerge', value: twMerge },
    ]
  },
  {
    module: '@/components/charts/AreaChart',
    exports: [
      { name: 'AreaChart', value: AreaChart },
    ]
  },
  {
    module: '@/components/ui/badge',
    exports: [
      { name: 'Badge', value: Badge },
    ]
  },
  {
    module: '@/components/ui/progress',
    exports: [
      { name: 'Progress', value: Progress },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@remixicon/react',
    exports: [
      { name: 'RiArrowLeftSLine', value: RiArrowLeftSLine },
      { name: 'RiArrowRightSLine', value: RiArrowRightSLine },
    ]
  },
  {
    module: 'recharts',
    exports: [
      { name: 'Area', value: Area },
      { name: 'CartesianGrid', value: CartesianGrid },
      { name: 'Dot', value: Dot },
      { name: 'Label', value: Label },
      { name: 'Line', value: Line },
      { name: 'AreaChart', value: AreaChart_2df1a179946854cc8ade8dd3596c5568763677e1 },
      { name: 'Legend', value: Legend },
      { name: 'ResponsiveContainer', value: ResponsiveContainer },
      { name: 'Tooltip', value: Tooltip },
      { name: 'XAxis', value: XAxis },
      { name: 'YAxis', value: YAxis },
    ]
  },
  {
    module: '@/components/lib/chartUtils',
    exports: [
      { name: 'AvailableChartColors', value: AvailableChartColors },
      { name: 'constructCategoryColors', value: constructCategoryColors },
      { name: 'getColorClassName', value: getColorClassName },
      { name: 'getYAxisDomain', value: getYAxisDomain },
      { name: 'hasOnlyOneValueForKey', value: hasOnlyOneValueForKey },
    ]
  },
  {
    module: '@/helpers/useOnWindowResize',
    exports: [
      { name: 'useOnWindowResize', value: useOnWindowResize },
    ]
  },
  {
    module: '@/components/lib/utils',
    exports: [
      { name: 'cx', value: cx },
    ]
  },
  {
    module: 'src/helpers/DateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
