// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useCallback, useEffect } from 'react';
import React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a from 'react';
import * as React from 'react';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import { cn } from 'components/lib/utils';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import * as SelectPrimitive from '@radix-ui/react-select';
import { CheckIcon, ChevronDownIcon, ChevronUpIcon, ChevronLeftIcon, ChevronRightIcon, Search, Plane, MapPin, CalendarIcon, Users, Star, Shield, Clock, Headphones, Wifi, Coffee, Luggage, Calendar as Calendar_6b289e2de0a07a8bed65fcf19e83723e986797b2, Heart, Share2, Facebook, Twitter, Linkedin, ArrowLeft, CreditCard, Phone, Mail, Instagram, Youtube, User, Thermometer, Camera, Bed, Navigation, Sun, Cloud } from 'lucide-react';
import * as PopoverPrimitive from '@radix-ui/react-popover';
import { DayPicker, getDefaultClassNames } from 'react-day-picker';
import { Button, buttonVariants } from 'components/ui/button';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import { useRouter, useSearchParams } from 'next/navigation';
import { usePreviewSearchActions, useSearchResultsActions, WidgetDataType, useSearchResults, widget, useQuestions, usePreviewSearch, FilterEqual, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import { PreviewSearch, SortSelect, Pagination, AccordionFacets, FacetItem, RangeFacet, SearchResultsAccordionFacets, SearchResultsFacetValueRange, Select, ArticleCard, CardViewSwitcher as CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 } from '@sitecore-search/ui';
import { GridIcon, ListBulletIcon, ArrowLeftIcon, ArrowRightIcon, CheckIcon as CheckIcon_1abd24cad8ff392456f872e6f12f5ac5d259c09e, ChevronDownIcon as ChevronDownIcon_1abd24cad8ff392456f872e6f12f5ac5d259c09e } from '@radix-ui/react-icons';
import { HIGHLIGHTED_ARTICLES_RFKID, SEARCH_WIDGET_ID, PREVIEW_WIDGET_ID, HOMEHIGHLIGHTED_WIDGET_ID, DEFAULT_IMG_URL } from '@/_data/customizations';
import HomeHighlighted from 'src/components/search/HomeHighlighted';
import Spinner from 'src/components/search/Spinner';
import ArticleItemCard from 'src/components/search/ArticleCard';
import SortOrder from 'src/components/search/SortOrder';
import ArticleHorizontalItemCard from 'src/components/search/ArticleHorizontalCard';
import SearchPagination from 'src/components/search/SearchPagination';
import SearchFacets from 'src/components/search/SearchFacets';
import ResultsPerPage from 'src/components/search/ResultsPerPage';
import QueryResultsSummary from 'src/components/search/QueryResultsSummary';
import CardViewSwitcher from 'src/components/search/CardViewSwitcher';
import { useSearchTracking } from 'src/hooks/useSearchTracking';
import SearchResultsWidget from 'src/components/search/SearchResultsComponent';
import QuestionsAnswers from 'src/components/search/QuestionsAnswers';
import { Accordion, Content, Header, Item, Trigger } from '@radix-ui/react-accordion';
import Image from 'next/image';
import SuggestionBlock from 'src/components/search/SuggestionBlock';
import { withDatasourceCheck, Text, Placeholder, RichText, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, Link as Link_8a80e63291fea86e0744df19113dc44bec187216, DateField, CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import { Input } from '@/components/ui/input';
import { Select as Select_74a315bf8f39737a75c686fc0a3118c1056b2a17, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button as Button_68caa79812567088b20baa54d6b10a9ef0e1581e } from '@/components/ui/button';
import Link from 'next/link';
import { useSearchTracking as useSearchTracking_28742e7434a136289865b7be7dae68a0db3267e1 } from '@/hooks/useSearchTracking';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { Badge } from '@/components/ui/badge';
import { newsDateFormatter } from 'src/helpers/DateHelper';
import { useI18n } from 'next-localization';
import PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 from 'src/components/search/PreviewSearch';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import Head from 'next/head';
import { removeTags } from 'src/helpers/ContentSearchHelper';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Separator } from '@/components/ui/separator';
import client from 'lib/sitecore-client';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useCallback', value: useCallback },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a },
      { name: '*', value: React },
    ]
  },
  {
    module: '@radix-ui/react-tabs',
    exports: [
      { name: '*', value: TabsPrimitive },
    ]
  },
  {
    module: 'components/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@radix-ui/react-separator',
    exports: [
      { name: '*', value: SeparatorPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-select',
    exports: [
      { name: '*', value: SelectPrimitive },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
      { name: 'ChevronUpIcon', value: ChevronUpIcon },
      { name: 'ChevronLeftIcon', value: ChevronLeftIcon },
      { name: 'ChevronRightIcon', value: ChevronRightIcon },
      { name: 'Search', value: Search },
      { name: 'Plane', value: Plane },
      { name: 'MapPin', value: MapPin },
      { name: 'CalendarIcon', value: CalendarIcon },
      { name: 'Users', value: Users },
      { name: 'Star', value: Star },
      { name: 'Shield', value: Shield },
      { name: 'Clock', value: Clock },
      { name: 'Headphones', value: Headphones },
      { name: 'Wifi', value: Wifi },
      { name: 'Coffee', value: Coffee },
      { name: 'Luggage', value: Luggage },
      { name: 'Calendar', value: Calendar_6b289e2de0a07a8bed65fcf19e83723e986797b2 },
      { name: 'Heart', value: Heart },
      { name: 'Share2', value: Share2 },
      { name: 'Facebook', value: Facebook },
      { name: 'Twitter', value: Twitter },
      { name: 'Linkedin', value: Linkedin },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'CreditCard', value: CreditCard },
      { name: 'Phone', value: Phone },
      { name: 'Mail', value: Mail },
      { name: 'Instagram', value: Instagram },
      { name: 'Youtube', value: Youtube },
      { name: 'User', value: User },
      { name: 'Thermometer', value: Thermometer },
      { name: 'Camera', value: Camera },
      { name: 'Bed', value: Bed },
      { name: 'Navigation', value: Navigation },
      { name: 'Sun', value: Sun },
      { name: 'Cloud', value: Cloud },
    ]
  },
  {
    module: '@radix-ui/react-popover',
    exports: [
      { name: '*', value: PopoverPrimitive },
    ]
  },
  {
    module: 'react-day-picker',
    exports: [
      { name: 'DayPicker', value: DayPicker },
      { name: 'getDefaultClassNames', value: getDefaultClassNames },
    ]
  },
  {
    module: 'components/ui/button',
    exports: [
      { name: 'Button', value: Button },
      { name: 'buttonVariants', value: buttonVariants },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useRouter', value: useRouter },
      { name: 'useSearchParams', value: useSearchParams },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'usePreviewSearchActions', value: usePreviewSearchActions },
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'useSearchResults', value: useSearchResults },
      { name: 'widget', value: widget },
      { name: 'useQuestions', value: useQuestions },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'useSearchResultsSelectedFilters', value: useSearchResultsSelectedFilters },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'PreviewSearch', value: PreviewSearch },
      { name: 'SortSelect', value: SortSelect },
      { name: 'Pagination', value: Pagination },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'RangeFacet', value: RangeFacet },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
      { name: 'SearchResultsFacetValueRange', value: SearchResultsFacetValueRange },
      { name: 'Select', value: Select },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'CardViewSwitcher', value: CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'GridIcon', value: GridIcon },
      { name: 'ListBulletIcon', value: ListBulletIcon },
      { name: 'ArrowLeftIcon', value: ArrowLeftIcon },
      { name: 'ArrowRightIcon', value: ArrowRightIcon },
      { name: 'CheckIcon', value: CheckIcon_1abd24cad8ff392456f872e6f12f5ac5d259c09e },
      { name: 'ChevronDownIcon', value: ChevronDownIcon_1abd24cad8ff392456f872e6f12f5ac5d259c09e },
    ]
  },
  {
    module: '@/_data/customizations',
    exports: [
      { name: 'HIGHLIGHTED_ARTICLES_RFKID', value: HIGHLIGHTED_ARTICLES_RFKID },
      { name: 'SEARCH_WIDGET_ID', value: SEARCH_WIDGET_ID },
      { name: 'PREVIEW_WIDGET_ID', value: PREVIEW_WIDGET_ID },
      { name: 'HOMEHIGHLIGHTED_WIDGET_ID', value: HOMEHIGHLIGHTED_WIDGET_ID },
      { name: 'DEFAULT_IMG_URL', value: DEFAULT_IMG_URL },
    ]
  },
  {
    module: 'src/components/search/HomeHighlighted',
    exports: [
      { name: 'default', value: HomeHighlighted },
    ]
  },
  {
    module: 'src/components/search/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/components/search/ArticleCard',
    exports: [
      { name: 'default', value: ArticleItemCard },
    ]
  },
  {
    module: 'src/components/search/SortOrder',
    exports: [
      { name: 'default', value: SortOrder },
    ]
  },
  {
    module: 'src/components/search/ArticleHorizontalCard',
    exports: [
      { name: 'default', value: ArticleHorizontalItemCard },
    ]
  },
  {
    module: 'src/components/search/SearchPagination',
    exports: [
      { name: 'default', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/search/SearchFacets',
    exports: [
      { name: 'default', value: SearchFacets },
    ]
  },
  {
    module: 'src/components/search/ResultsPerPage',
    exports: [
      { name: 'default', value: ResultsPerPage },
    ]
  },
  {
    module: 'src/components/search/QueryResultsSummary',
    exports: [
      { name: 'default', value: QueryResultsSummary },
    ]
  },
  {
    module: 'src/components/search/CardViewSwitcher',
    exports: [
      { name: 'default', value: CardViewSwitcher },
    ]
  },
  {
    module: 'src/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking },
    ]
  },
  {
    module: 'src/components/search/SearchResultsComponent',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: 'src/components/search/QuestionsAnswers',
    exports: [
      { name: 'default', value: QuestionsAnswers },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'Content', value: Content },
      { name: 'Header', value: Header },
      { name: 'Item', value: Item },
      { name: 'Trigger', value: Trigger },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: 'src/components/search/SuggestionBlock',
    exports: [
      { name: 'default', value: SuggestionBlock },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Text', value: Text },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'DateField', value: DateField },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: '@/components/ui/input',
    exports: [
      { name: 'Input', value: Input },
    ]
  },
  {
    module: '@/components/ui/select',
    exports: [
      { name: 'Select', value: Select_74a315bf8f39737a75c686fc0a3118c1056b2a17 },
      { name: 'SelectContent', value: SelectContent },
      { name: 'SelectItem', value: SelectItem },
      { name: 'SelectTrigger', value: SelectTrigger },
      { name: 'SelectValue', value: SelectValue },
    ]
  },
  {
    module: '@/components/ui/button',
    exports: [
      { name: 'Button', value: Button_68caa79812567088b20baa54d6b10a9ef0e1581e },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: '@/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking_28742e7434a136289865b7be7dae68a0db3267e1 },
    ]
  },
  {
    module: '@/components/ui/card',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardContent', value: CardContent },
      { name: 'CardHeader', value: CardHeader },
      { name: 'CardTitle', value: CardTitle },
    ]
  },
  {
    module: '@/components/ui/popover',
    exports: [
      { name: 'Popover', value: Popover },
      { name: 'PopoverContent', value: PopoverContent },
      { name: 'PopoverTrigger', value: PopoverTrigger },
    ]
  },
  {
    module: '@/components/ui/calendar',
    exports: [
      { name: 'Calendar', value: Calendar },
    ]
  },
  {
    module: '@/components/ui/badge',
    exports: [
      { name: 'Badge', value: Badge },
    ]
  },
  {
    module: 'src/helpers/DateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'src/components/search/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'clsx', value: clsx },
    ]
  },
  {
    module: 'tailwind-merge',
    exports: [
      { name: 'twMerge', value: twMerge },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'src/helpers/ContentSearchHelper',
    exports: [
      { name: 'removeTags', value: removeTags },
    ]
  },
  {
    module: '@/components/ui/tabs',
    exports: [
      { name: 'Tabs', value: Tabs },
      { name: 'TabsContent', value: TabsContent },
      { name: 'TabsList', value: TabsList },
      { name: 'TabsTrigger', value: TabsTrigger },
    ]
  },
  {
    module: '@/components/ui/separator',
    exports: [
      { name: 'Separator', value: Separator },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
