// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, Placeholder, RichText, NextImage, withDatasourceCheck, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useState, useId, useEffect } from 'react';
import React from 'react';
import { useTheme } from 'next-themes';
import { faFacebook, faInstagram, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import BlobAccent from '@/assets/shapes/BlobAccent';
import { CommonStyles, FeatureStyles } from '@/types/styleFlags';
import { faArrowRight, faBars, faChevronDown, faChevronUp, faTimes, faEnvelope, faPhone, faArrowLeft } from '@fortawesome/free-solid-svg-icons';
import BlobAccent_c450f25c63b00a2e370305e155038c473dbb9c49 from 'src/components/non-sitecore/BlobAccent';
import CurvedClip from 'src/components/non-sitecore/CurvedClip';
import { getLinkField, getNavigationText } from '@/helpers/navHelpers';
import { useI18n } from 'next-localization';
import HeroClip from '@/assets/shapes/HeroClip';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import BlobAccent_2e4ecd85952329c540c505e64c2c0c7c0394fc8b from 'src/assets/shapes/BlobAccent';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Keyboard, Navigation, Pagination } from 'swiper/modules';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import CurvedClip_a87a03c0e7ca8cbf6425a5f9fe21d118e0f2a53f from 'src/assets/shapes/CurvedClip';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useId', value: useId },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next-themes',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: '@fortawesome/free-brands-svg-icons',
    exports: [
      { name: 'faFacebook', value: faFacebook },
      { name: 'faInstagram', value: faInstagram },
      { name: 'faTwitter', value: faTwitter },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: '@/assets/shapes/BlobAccent',
    exports: [
      { name: 'default', value: BlobAccent },
    ]
  },
  {
    module: '@/types/styleFlags',
    exports: [
      { name: 'CommonStyles', value: CommonStyles },
      { name: 'FeatureStyles', value: FeatureStyles },
    ]
  },
  {
    module: '@fortawesome/free-solid-svg-icons',
    exports: [
      { name: 'faArrowRight', value: faArrowRight },
      { name: 'faBars', value: faBars },
      { name: 'faChevronDown', value: faChevronDown },
      { name: 'faChevronUp', value: faChevronUp },
      { name: 'faTimes', value: faTimes },
      { name: 'faEnvelope', value: faEnvelope },
      { name: 'faPhone', value: faPhone },
      { name: 'faArrowLeft', value: faArrowLeft },
    ]
  },
  {
    module: 'src/components/non-sitecore/BlobAccent',
    exports: [
      { name: 'default', value: BlobAccent_c450f25c63b00a2e370305e155038c473dbb9c49 },
    ]
  },
  {
    module: 'src/components/non-sitecore/CurvedClip',
    exports: [
      { name: 'default', value: CurvedClip },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkField', value: getLinkField },
      { name: 'getNavigationText', value: getNavigationText },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@/assets/shapes/HeroClip',
    exports: [
      { name: 'default', value: HeroClip },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'src/assets/shapes/BlobAccent',
    exports: [
      { name: 'default', value: BlobAccent_2e4ecd85952329c540c505e64c2c0c7c0394fc8b },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Keyboard', value: Keyboard },
      { name: 'Navigation', value: Navigation },
      { name: 'Pagination', value: Pagination },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: 'src/assets/shapes/CurvedClip',
    exports: [
      { name: 'default', value: CurvedClip_a87a03c0e7ca8cbf6425a5f9fe21d118e0f2a53f },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
